// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJd8beOBOV1U5Dnx-S3XwooYVOxY9KSe4',
    appId: '1:425277120843:web:6d9cbdcc261924acd608ce',
    messagingSenderId: '425277120843',
    projectId: 'annahomestay-ea338',
    authDomain: 'annahomestay-ea338.firebaseapp.com',
    storageBucket: 'annahomestay-ea338.appspot.com',
    measurementId: 'G-YB7B4RKVZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh2ZTakhcdRWIWYxTZjTa4-u1y6c754Wc',
    appId: '1:425277120843:android:bc924e9d108b4e67d608ce',
    messagingSenderId: '425277120843',
    projectId: 'annahomestay-ea338',
    storageBucket: 'annahomestay-ea338.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzKTnCKVLXPteRItM4zf-pb9yLuxZTX-g',
    appId: '1:425277120843:ios:3692f01581f09f75d608ce',
    messagingSenderId: '425277120843',
    projectId: 'annahomestay-ea338',
    storageBucket: 'annahomestay-ea338.appspot.com',
    androidClientId: '425277120843-psrdr34j19t61q55gi9mb885op56itoe.apps.googleusercontent.com',
    iosClientId: '425277120843-lfvekgdlmcameglfonp4us5uf8dudbq8.apps.googleusercontent.com',
    iosBundleId: 'com.google.firebase.presents.annahomestay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzKTnCKVLXPteRItM4zf-pb9yLuxZTX-g',
    appId: '1:425277120843:ios:12d97028fec4d0d9d608ce',
    messagingSenderId: '425277120843',
    projectId: 'annahomestay-ea338',
    storageBucket: 'annahomestay-ea338.appspot.com',
    androidClientId: '425277120843-psrdr34j19t61q55gi9mb885op56itoe.apps.googleusercontent.com',
    iosClientId: '425277120843-0g9231ftl748cugq6a37603oasgd5771.apps.googleusercontent.com',
    iosBundleId: 'com.google.firebase.presents.annahomestay.RunnerTests',
  );
}
